/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://iv4pzutsifb6viscfqebzrge5y.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-czgjzbtoobce5kxlpomnwfuo3a",
    "aws_cognito_identity_pool_id": "eu-west-2:b25a4001-42c4-4d5d-8556-7575f17c7856",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_vpg6bWGLp",
    "aws_user_pools_web_client_id": "73kc4f414gghpcl577rjb22tm9",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
